---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# MATH-516 Applied Statistics

<!-- badges: start -->
<!-- badges: end -->

All course materials will come here, in this repo. Check out [this manual](https://htmlpreview.github.io/?https://github.com/TMasak/StatComp/blob/master/Manuals/02_Github.html) from the previous course (a mandatory prerequisite) to see how to pull this repo (do not manually download the slides, etc.).

Moodle will only be used for formal submission (a link to a Github repo to be uploaded into the respective Moodle assignment).

# Content and Evaluation

See the slides for Week 1.

# Acknowledgements

This course was partially inspired by various existing courses, and the credit goes to their creators:

* Michal Kulich & Arnost Komarek, Charles University,
* Bin Yu, UC Berkeley,
* Reinhard Furrer, University of Zurich,
* Claudia Klüppelberg, Technical University of Munich,
* Juliette Blanchet (Université Grenoble Alpes) & Jennifer Wadsworth (Lancaster University), previously EPFL,
* Mehdi Gholam, EPFL.

  
  
  


